"""The metering run has to go all the way through before anything is bought.

340 found that 337's ten paid audio calls left no ledger row: the meter was
never in the client stack, so `pricing_complete`, `unpriced_models` and the
dollar figure in that report were four constants this script wrote afterwards.
342 registers a two-call trial that would show the path reconnected.

A trial that has only ever been described is not a trial. This file runs it --
render, encode, prompt, wire, meter, reserve, settle, price, receipt, report,
check -- with no network and no credential, and then asks the questions 342 §6
says the paid run will be asked. What it can prove is that the plumbing carries
a row from one end to the other; what it cannot prove is anything at all about
`gpt-audio-1.5`, which is why every artifact it produces says `rehearsal` and
every row in its ledger says `provider: stub`.

The corpus here is **synthetic**: two tones, not 330's speech. The pinned clips
are a CI artifact and eSpeak is not installed on every machine that runs these
tests, and a corpus regenerated by a different eSpeak is exactly what
`load_speech_corpus` is built to refuse. So this file builds its own, with its
own manifest and its own rehearsal document, and never points the real
pre-registration at it -- 342's document stays pinned to 330's manifest, and
the swap-detection test below is the reason that pin exists.
"""

from __future__ import annotations

import hashlib
import importlib.util
import json
import math
import struct
import sys
import wave
from pathlib import Path
from typing import Any

import pytest

REPO_ROOT = Path(__file__).resolve().parents[2]
BATCH_RUNNER = REPO_ROOT / "batch-runner"
if str(BATCH_RUNNER) not in sys.path:
    sys.path.insert(0, str(BATCH_RUNNER))

from core.cost_receipts import load_receipt_price_table  # noqa: E402

SCRIPTS = BATCH_RUNNER / "scripts"


def _load(name: str):
    """Import a script by path -- ``scripts/`` is not an importable package."""
    spec = importlib.util.spec_from_file_location(name, SCRIPTS / f"{name}.py")
    assert spec and spec.loader
    module = importlib.util.module_from_spec(spec)
    sys.modules[spec.name] = module
    spec.loader.exec_module(module)
    return module


measure = _load("measure_audio_grading_accuracy")
checker = _load("verify_audio_metering_run")

#: 16 kHz mono, which is what the grading path delivers and what the manifest
#: pins. The tone frequency is irrelevant to everything downstream -- the stub
#: does not listen -- but the two clips are given different lengths on purpose
#: so their payloads, and therefore their ``request_sha256``, differ. A
#: duplicate row is then visible at the payload level and not only by call id.
SAMPLE_RATE_HZ = 16000
CLIP_SECONDS = {"crate": 3.0, "shelf": 2.5}

#: The two claims 342 §2 fixes, and the two that pair with them. All four are
#: in the manifest because ``load_speech_corpus`` requires the corpus to be
#: balanced and every pair to hold one true and one false; the run narrows to
#: the two named in the document, which is the same narrowing 337's pilot did.
NARROWED_TO = ("crate_seventeen", "shelf_fifty")


def _render_clip(path: Path, seconds: float) -> dict[str, Any]:
    frames = int(seconds * SAMPLE_RATE_HZ)
    body = b"".join(
        struct.pack("<h", int(12000 * math.sin(2 * math.pi * 440.0 * n / SAMPLE_RATE_HZ)))
        for n in range(frames)
    )
    with wave.open(str(path), "wb") as handle:
        handle.setnchannels(1)
        handle.setsampwidth(2)
        handle.setframerate(SAMPLE_RATE_HZ)
        handle.writeframes(body)
    raw = path.read_bytes()
    return {
        "file": path.name,
        "sha256": hashlib.sha256(raw).hexdigest(),
        "bytes": len(raw),
        "format": "wav",
        "channels": 1,
        "sample_width_bytes": 2,
        "sample_rate_hz": SAMPLE_RATE_HZ,
        "frames": frames,
        "seconds": round(frames / SAMPLE_RATE_HZ, 4),
    }


def _claim(claim_id: str, pair_id: str, clip_id: str, word: str, holds: bool):
    return {
        "claim_id": claim_id,
        "pair_id": pair_id,
        "clip_id": clip_id,
        "family": "confusable_number",
        "criterion": f"The speaker states a quantity of {word}.",
        "holds": holds,
        "because": f"synthetic rehearsal claim, {'true' if holds else 'false'}",
    }


@pytest.fixture(scope="module")
def corpus(tmp_path_factory) -> dict[str, Any]:
    """Two tones, a manifest that pins them, and the digest of that manifest.

    Module-scoped: the clips are read-only for every test here and rendering
    them is the slowest thing in the file.
    """
    root = tmp_path_factory.mktemp("rehearsal-corpus")
    clips = root / "clips"
    clips.mkdir()
    manifest = {
        "kind": "synthetic-rehearsal-corpus",
        "not_the_pinned_set": (
            "Tones, not speech, generated by the test suite. This exists so "
            "the metering path can be run end to end offline. It is not 330's "
            "corpus and no accuracy may be read off it."
        ),
        "clips": [
            {
                "clip_id": clip_id,
                "sent": _render_clip(clips / f"{clip_id}.sent.wav", seconds),
            }
            for clip_id, seconds in CLIP_SECONDS.items()
        ],
        "claims": [
            _claim("crate_seventeen", "crate_number", "crate", "seventeen", True),
            _claim("crate_seventy", "crate_number", "crate", "seventy", False),
            _claim("shelf_fifteen", "shelf_number", "shelf", "fifteen", True),
            _claim("shelf_fifty", "shelf_number", "shelf", "fifty", False),
        ],
    }
    path = root / "rehearsal-manifest.json"
    path.write_text(
        json.dumps(manifest, indent=2, ensure_ascii=False) + "\n", encoding="utf-8"
    )
    return {
        "manifest": path,
        "clips": clips,
        "sha256": hashlib.sha256(path.read_bytes()).hexdigest(),
    }


def _document(
    path: Path,
    *,
    corpus: dict[str, Any],
    kind: str = measure.AUDIO_COST_METERING_KIND,
    grader: str | None = None,
    price: str | None = None,
    manifest: str | None = None,
    claims: tuple[str, ...] = NARROWED_TO,
) -> Path:
    """A rehearsal document in the shape the dispatcher reads.

    Every pin is overridable because the refusals below are exactly the cases
    where one of them is wrong, and a test that could not write a wrong
    document could not show the dispatcher noticing.
    """
    if grader is None:
        grader = measure.grader_source_hash(measure.PINNED_CONFIG)
    if price is None:
        price = load_receipt_price_table().sha256
    if manifest is None:
        manifest = corpus["sha256"]
    listed = ", ".join(f"`{claim_id}`" for claim_id in claims)
    path.write_text(
        "# REHEARSAL ONLY — this is not a pre-registration\n"
        "\n"
        "Written by the test suite. It pins a synthetic corpus of tones and\n"
        "buys nothing. 342's real document is not this file.\n"
        "\n"
        "| | 값 |\n"
        "|---|---|\n"
        f"| 진단 종류 | `{kind}` |\n"
        f"| 채점기 지문 | `{grader}` |\n"
        f"| 가격표 지문 | `{price}` |\n"
        f"| 매니페스트 지문 | `{manifest}` |\n"
        f"| 시험 문항 | {listed} |\n",
        encoding="utf-8",
    )
    return path


def _argv(tmp_path: Path, corpus: dict[str, Any], document: Path, **extra) -> list[str]:
    argv = [
        "--dry-run",
        "--repeats", "1",
        "--metering-run", str(document),
        "--speech-set", str(extra.pop("speech_set", corpus["manifest"])),
        "--speech-clips", str(corpus["clips"]),
        "--out", str(tmp_path / "report.json"),
    ]
    ledger = extra.pop("cost_ledger", tmp_path / "probe.cost_ledger.sqlite3")
    if ledger is not None:
        argv += ["--cost-ledger", str(ledger)]
    for flag, value in extra.items():
        argv += [f"--{flag.replace('_', '-')}", str(value)]
    return argv


def _run(tmp_path: Path, corpus: dict[str, Any], document: Path, **extra):
    code = measure.main(_argv(tmp_path, corpus, document, **extra))
    return code, tmp_path / "report.json"


def _condition(outcome, number):
    for entry in outcome["conditions"]:
        if entry["condition"] == number:
            return entry
    raise AssertionError(f"no condition {number}")


# ── the rehearsal, end to end ────────────────────────────────────────────


def test_the_registered_run_reaches_rehearsal_ok(tmp_path, corpus):
    """Every line from the manifest to the verdict, with nothing bought."""
    document = _document(tmp_path / "prereg.md", corpus=corpus)
    code, report_path = _run(tmp_path, corpus, document)
    assert code == 0

    outcome = checker.check(report_path)
    assert outcome["counts"]["failed"] == 0, [
        entry for entry in outcome["conditions"] if entry["result"] == "fail"
    ]
    assert outcome["verdict"] == checker.VERDICT_REHEARSAL_OK
    assert outcome["record_kind"] == "rehearsal"
    # Condition 2 is the one a stub cannot answer, and it is recorded as
    # unanswerable rather than passed. A rehearsal that scored nine of nine
    # would be the artifact most easily mistaken for the paid run.
    assert _condition(outcome, 2)["result"] == checker.RESULT_UNANSWERABLE
    # 343 §2.2 quotes this line, and 343 §3.5 says the eight endings did not
    # move it. Both claims are only as good as an exact count: "nothing
    # failed" plus "condition 2 is unanswerable" would still hold if a second
    # condition quietly stopped answering, and the document would go on
    # reporting 8/0/1.
    assert outcome["counts"] == {"passed": 8, "failed": 0, "unanswerable": 1}
    assert "8 passed, 0 failed, 1 unanswerable" in checker.render(outcome)
    assert checker.main([str(report_path)]) == 0


def test_the_run_sends_exactly_the_two_registered_calls(tmp_path, corpus):
    """Two claims, one repeat, one arm. Two requests, two rows, no third."""
    document = _document(tmp_path / "prereg.md", corpus=corpus)
    _, report_path = _run(tmp_path, corpus, document)
    report = json.loads(report_path.read_text(encoding="utf-8"))

    assert [call["claim_id"] for call in report["calls"]] == list(NARROWED_TO)
    assert report["cost"]["model_calls"] == 2
    assert report["cost"]["ledger"]["rows"] == 2
    assert report["metering"]["registered"] == {
        "claims": measure.AUDIO_COST_METERING_CLAIMS,
        "repeats": 1,
        "arms": 1,
        "planned_calls": 2,
        "request_cap": measure.SPEECH_REQUEST_CAPS[measure.AUDIO_COST_METERING_KIND],
        "wall_clock_seconds": measure.AUDIO_COST_METERING_WALL_CLOCK_SECONDS,
        "sdk_max_retries": measure.AUDIO_COST_METERING_SDK_RETRIES,
        "failure_budget": measure.AUDIO_COST_METERING_FAILURE_BUDGET,
    }


def test_nothing_the_rehearsal_writes_can_be_read_as_a_bill(tmp_path, corpus):
    """Separated at three layers, because one of them will be skimmed.

    The cost block says which kind of record it is; every ledger row names a
    provider that does not sell anything; and the amount is absent rather than
    zero. A reader who only sees one of the three still cannot mistake this.
    """
    document = _document(tmp_path / "prereg.md", corpus=corpus)
    _, report_path = _run(tmp_path, corpus, document)
    report = json.loads(report_path.read_text(encoding="utf-8"))

    assert report["measured"] is False
    assert report["cost"]["record_kind"] == "rehearsal"
    assert report["cost"]["billable_calls"] == 0
    assert report["cost"]["estimated_cost_usd"] is None
    assert report["cost"]["pricing_complete"] is False

    rows = [
        json.loads(line)
        for line in Path(report["cost"]["ledger"]["path"])
        .read_text(encoding="utf-8")
        .splitlines()
        if line.strip()
    ]
    assert [row["provider"] for row in rows] == [measure.STUB_PROVIDER] * 2
    assert [row["resolved_model"] for row in rows] == [measure.STUB_MODEL] * 2
    assert all(row["model_cost_usd"] in (None, 0.0) for row in rows)

    assert "rehearsal" in checker.render(checker.check(report_path)).lower()


def test_a_rehearsal_ledger_refuses_to_take_a_paid_row(tmp_path, corpus):
    """One file, one kind. A mixed total is part invoice and part dress run.

    The refusal is checked from the rehearsal side because that is the side
    that can be tested without buying anything, and the rule is symmetric: the
    dispatcher compares the run's kind against the kinds already in the file.
    """
    document = _document(tmp_path / "prereg.md", corpus=corpus)
    ledger = tmp_path / "probe.cost_ledger.sqlite3"
    assert _run(tmp_path, corpus, document, cost_ledger=ledger)[0] == 0

    # Re-open the same file and put a measured row in it, the way a paid run
    # would. No model is called: only the bookkeeping shape matters here.
    from core.cost_receipts import (
        RETRY_NONE,
        STAGE_PERCEPTION,
        CostReceiptLedger,
        make_call_id,
    )

    with CostReceiptLedger(
        ledger, run_id="paid-run", price_table=load_receipt_price_table()
    ) as paid:
        paid.reserve(
            call_id=make_call_id(
                run_id="paid-run",
                task_id="audio_accuracy_diagnostic",
                stage=STAGE_PERCEPTION,
                retry_kind=RETRY_NONE,
                attempt_index=0,
                sequence=99,
            ),
            task_id="audio_accuracy_diagnostic",
            stage=STAGE_PERCEPTION,
            retry_kind=RETRY_NONE,
            provider="azure",
            requested_model="gpt-audio-1.5",
            deployment="gpt-audio-1.5",
            api_version="2025-04-01-preview",
            request_sha256="0" * 64,
        )
        # Asserted before the dispatch, so a code 3 for some unrelated reason
        # cannot be read as this refusal firing.
        assert measure.ledger_record_kinds(paid) >= {"rehearsal", "measured"}

    code, _ = _run(tmp_path, corpus, document, cost_ledger=ledger)
    assert code == 3


# ── a broken verdict is not a lost cost row ──────────────────────────────


class _StubThatBreaks:
    """Answers badly on purpose: one unparseable reply, one refusal to judge.

    337's replies mostly failed to parse, and a metering path that settled
    after parsing would have lost exactly those calls -- the calls that were
    charged for. Both shapes are produced here because they take different
    branches in ``AudioPerception.judge``: the first raises out of the envelope
    parser, the second returns normally with a verdict that declines.
    """

    def __init__(self, claims) -> None:
        self._order = [claim.criterion for claim in claims]
        self.requests: list[dict[str, Any]] = []
        self.chat = type("_Chat", (), {"completions": self})()

    def create(self, **kwargs: Any) -> Any:
        self.requests.append(kwargs)
        text = ""
        b64_chars = 0
        for part in kwargs["messages"][0]["content"]:
            if part.get("type") == "text":
                text = part["text"]
            elif part.get("type") == "input_audio":
                b64_chars = len((part.get("input_audio") or {}).get("data") or "")
        first = self._order and self._order[0] in text
        body = (
            "I listened to the clip and I think ... " if first
            else json.dumps(
                {
                    "verdict": "judge_error",
                    "partial_score": 0.0,
                    "evidence": "",
                    "confidence": 0.0,
                    "reasoning": "stub: declining to judge",
                }
            )
        )
        return measure._StubResponse(body, b64_chars=b64_chars)


def test_an_unreadable_reply_and_a_refusal_both_keep_their_cost_rows(
    tmp_path, corpus, monkeypatch
):
    """The question this trial asks is about rows, not about verdicts.

    Neither call produced a judgement, so the script exits 2: nothing was
    measured. That is the *accuracy* question going unanswered, and it is the
    exit code 337 would have earned. The cost question is answered anyway --
    both calls were sent, both consumed tokens, both are on the ledger, and
    the receipt is closed from a ``finally`` that runs on this path too.

    Failing here would mean a run's spend disappears exactly when its replies
    break, which is the shape of run 34008840627: 52 of its calls produced no
    verdict and every one of them was paid for.
    """
    monkeypatch.setattr(measure, "TruthfulStub", _StubThatBreaks)
    document = _document(tmp_path / "prereg.md", corpus=corpus)
    code, report_path = _run(tmp_path, corpus, document)
    assert code == 2

    report = json.loads(report_path.read_text(encoding="utf-8"))
    errors = [call["judge_error"] for call in report["calls"]]
    assert all(errors), errors
    assert any(error.startswith("format_error:") for error in errors), errors
    assert "sub_judge_declined" in errors, errors

    assert report["cost"]["model_calls"] == 2
    assert report["cost"]["ledger"]["rows"] == 2
    assert Path(report["cost"]["ledger"]["path"]).is_file()

    outcome = checker.check(report_path)
    seventh = _condition(outcome, 7)
    assert seventh["result"] == "pass"
    assert seventh["data"]["calls_with_judge_error"] == 2
    assert outcome["counts"]["failed"] == 0
    assert outcome["verdict"] == checker.VERDICT_REHEARSAL_OK


def test_the_accuracy_of_a_broken_run_is_not_what_decides_it(
    tmp_path, corpus, monkeypatch
):
    """Zero answered claims, and the metering verdict is still ok.

    342 §1 says accuracy is 337/338's question and not this one. If a run
    where nothing was judged could not pass, the trial would be measuring the
    sub-judge again by accident -- and the two exit codes are how the two
    questions stay apart: 2 from the measurement script, 0 from the checker.
    """
    monkeypatch.setattr(measure, "TruthfulStub", _StubThatBreaks)
    document = _document(tmp_path / "prereg.md", corpus=corpus)
    code, report_path = _run(tmp_path, corpus, document)
    report = json.loads(report_path.read_text(encoding="utf-8"))

    answered = [call for call in report["calls"] if not call["judge_error"]]
    assert answered == []
    assert code == 2
    assert checker.main([str(report_path)]) == 0
    assert checker.check(report_path)["verdict"] == checker.VERDICT_REHEARSAL_OK


# ── a run stopped by its ceiling still exports what it spent ─────────────


def test_a_run_stopped_by_its_ceiling_still_exports_its_rows(
    tmp_path, corpus, monkeypatch
):
    """The ceiling exists to stop spending, not to erase the record of it.

    342 §5 sets the cap at 6 against a plan of 2, so a correct run never
    approaches it; the only way to see this path is to tighten the ceiling
    until the second request trips it. What matters is what survives: the
    first request went out, it is on the ledger, and the export happens from
    the ``finally``. Exporting only on success would delete the record of
    exactly the spend nobody planned for.
    """

    class _WireWithATighterCap(measure.WireClient):
        def __init__(self, *args: Any, **kwargs: Any) -> None:
            kwargs["request_cap"] = 1
            super().__init__(*args, **kwargs)

    monkeypatch.setattr(measure, "WireClient", _WireWithATighterCap)
    document = _document(tmp_path / "prereg.md", corpus=corpus)
    code, report_path = _run(tmp_path, corpus, document)
    assert code == 3

    report = json.loads(report_path.read_text(encoding="utf-8"))
    assert report["stopped"]["rule"] == "request_cap"
    ledger = Path(report["cost"]["ledger"]["path"])
    assert ledger.is_file()
    assert report["cost"]["ledger"]["rows"] == 1
    assert report["cost"]["record_kind"] == "rehearsal"


def test_the_registered_ceiling_refuses_a_plan_that_does_not_fit_it(
    tmp_path, corpus, monkeypatch, capsys
):
    """Checked before the client, so the refusal costs nothing.

    The repair when this fires is to re-plan. Raising the ceiling to fit the
    run it just refused is the one repair that is not available, and 342 §5
    says so in the document rather than only in the code.
    """
    monkeypatch.setitem(
        measure.SPEECH_REQUEST_CAPS, measure.AUDIO_COST_METERING_KIND, 1
    )
    document = _document(tmp_path / "prereg.md", corpus=corpus)
    code, report_path = _run(tmp_path, corpus, document)
    assert code == 3
    assert "does not fit the ceiling it registered" in capsys.readouterr().err
    assert not report_path.exists()


# ── the dispatcher's refusals ────────────────────────────────────────────


def test_a_document_registering_another_diagnostic_is_refused(tmp_path, corpus, capsys):
    document = _document(
        tmp_path / "prereg.md", corpus=corpus, kind=measure.SPEECH_FORMAT_PILOT_KIND
    )
    code, _ = _run(tmp_path, corpus, document)
    assert code == 3
    assert measure.SPEECH_FORMAT_PILOT_KIND in capsys.readouterr().err


def test_a_document_fixing_one_claim_is_refused(tmp_path, corpus, capsys):
    """One row cannot show the second was not the first counted twice."""
    document = _document(
        tmp_path / "prereg.md", corpus=corpus, claims=("crate_seventeen",)
    )
    code, _ = _run(tmp_path, corpus, document)
    assert code == 3
    assert "counted twice" in capsys.readouterr().err


def test_a_document_fixing_three_claims_is_refused(tmp_path, corpus, capsys):
    """And a third buys a call that shows nothing the second did not."""
    document = _document(
        tmp_path / "prereg.md",
        corpus=corpus,
        claims=("crate_seventeen", "shelf_fifty", "shelf_fifteen"),
    )
    code, _ = _run(tmp_path, corpus, document)
    assert code == 3
    assert "registered for exactly 2" in capsys.readouterr().err


def test_a_dispatch_asking_for_more_repeats_than_registered_is_refused(
    tmp_path, corpus, capsys
):
    document = _document(tmp_path / "prereg.md", corpus=corpus)
    code = measure.main(_argv(tmp_path, corpus, document)[:1] + [
        "--repeats", "3",
        "--metering-run", str(document),
        "--speech-set", str(corpus["manifest"]),
        "--speech-clips", str(corpus["clips"]),
        "--cost-ledger", str(tmp_path / "probe.cost_ledger.sqlite3"),
        "--out", str(tmp_path / "report.json"),
    ])
    assert code == 3
    assert "Dispatch it as registered" in capsys.readouterr().err


def test_a_substituted_corpus_is_caught_by_the_manifest_pin(tmp_path, corpus, capsys):
    """The clips check out. Against their own manifest, which is the point.

    A corpus swapped for one regenerated this morning is internally consistent
    and passes every digest ``load_speech_corpus`` checks, because the file
    making the claims is the file being checked. The document's pin is what
    turns that consistency into identity.
    """
    swapped = tmp_path / "swapped-manifest.json"
    manifest = json.loads(corpus["manifest"].read_text(encoding="utf-8"))
    manifest["note_added_after_pinning"] = "one byte of drift"
    swapped.write_text(json.dumps(manifest, indent=2) + "\n", encoding="utf-8")
    assert hashlib.sha256(swapped.read_bytes()).hexdigest() != corpus["sha256"]

    document = _document(tmp_path / "prereg.md", corpus=corpus)
    code, _ = _run(tmp_path, corpus, document, speech_set=swapped)
    assert code == 3
    error = capsys.readouterr().err
    assert "not the speech manifest" in error
    assert "which is the check a substituted corpus" in error


def test_a_price_table_that_moved_since_the_document_is_refused(
    tmp_path, corpus, capsys
):
    """This run's whole output is a cost record, so the rate card is pinned.

    Between registration and dispatch, one added line for `gpt-audio-1.5`
    would turn the expected `null` into a complete-looking amount nobody
    agreed to.
    """
    document = _document(tmp_path / "prereg.md", corpus=corpus, price="a" * 64)
    code, _ = _run(tmp_path, corpus, document)
    assert code == 3
    assert "not the price table" in capsys.readouterr().err


def test_a_grader_that_moved_since_the_document_is_refused(tmp_path, corpus, capsys):
    document = _document(tmp_path / "prereg.md", corpus=corpus, grader="b" * 64)
    code, _ = _run(tmp_path, corpus, document)
    assert code == 3
    assert "not the grader" in capsys.readouterr().err


def test_the_metering_run_will_not_dispatch_without_a_ledger(tmp_path, corpus):
    """Elsewhere a missing ledger is a warning. Here it is the whole question.

    A metering trial without `--cost-ledger` buys audio calls to answer a
    question it then cannot answer, which is the one outcome worse than not
    running it.
    """
    document = _document(tmp_path / "prereg.md", corpus=corpus)
    with pytest.raises(SystemExit) as raised:
        _run(tmp_path, corpus, document, cost_ledger=None)
    assert raised.value.code == 2


def test_the_metering_run_and_the_prompt_comparison_are_not_the_same_door(
    tmp_path, corpus
):
    """Two diagnostics, two documents, two questions. Neither opens the other."""
    document = _document(tmp_path / "prereg.md", corpus=corpus)
    with pytest.raises(SystemExit) as raised:
        measure.main(
            _argv(tmp_path, corpus, document) + ["--speech-prompt-ab", str(document)]
        )
    assert raised.value.code == 2


def test_a_metering_document_handed_to_the_prompt_comparison_is_refused(
    tmp_path, corpus, capsys
):
    """The other direction: the A/B door checks the kind too."""
    document = _document(tmp_path / "prereg.md", corpus=corpus)
    code = measure.main([
        "--dry-run",
        "--repeats", "1",
        "--speech-prompt-ab", str(document),
        "--speech-set", str(corpus["manifest"]),
        "--speech-clips", str(corpus["clips"]),
        "--out", str(tmp_path / "report.json"),
    ])
    assert code == 3
    assert measure.AUDIO_COST_METERING_KIND in capsys.readouterr().err


# ── what the trial was registered as, recorded next to what it did ───────


def test_the_report_records_what_it_was_held_to_without_copying_it_twice(
    tmp_path, corpus
):
    """Provenance with a single home for each digest.

    Two copies of a fingerprint eventually disagree, and when they do there is
    no way to tell which one is the right one. So the metering block carries
    only what has nowhere else to live; the clip digests, the model and the
    price table stay where they already were.
    """
    document = _document(tmp_path / "prereg.md", corpus=corpus)
    _, report_path = _run(tmp_path, corpus, document)
    report = json.loads(report_path.read_text(encoding="utf-8"))
    block = report["metering"]

    assert block["diagnostic_kind"] == measure.AUDIO_COST_METERING_KIND
    assert block["preregistration"]["sha256"] == hashlib.sha256(
        document.read_bytes()
    ).hexdigest()
    assert block["speech_manifest"]["sha256"] == corpus["sha256"]
    assert block["grading_config"]["sha256"] == hashlib.sha256(
        measure.PINNED_CONFIG.read_bytes()
    ).hexdigest()

    serialized = json.dumps(block)
    assert report["cost"]["price_table"]["sha256"] not in serialized
    assert report["pins"]["grader_source_sha256"] not in serialized
    for digest in report["clip_sha256"].values():
        assert digest not in serialized
